# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imagies.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

root_folder = 'C:/Users/Asus/Desktop/projects/SpeechRecognition/img'


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(10, 0, 781, 451))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap(root_folder + '/Roune.jpg'))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.button_house = QtWidgets.QPushButton(self.centralwidget)
        self.button_house.setGeometry(QtCore.QRect(60, 460, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.button_house.setFont(font)
        self.button_house.setObjectName("button_house")
        self.button_canary = QtWidgets.QPushButton(self.centralwidget)
        self.button_canary.setGeometry(QtCore.QRect(420, 460, 351, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.button_canary.setFont(font)
        self.button_canary.setObjectName("button_canary")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.button_canary.clicked.connect(self.show_canary)
        self.button_house.clicked.connect(self.show_house)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_house.setText(_translate("MainWindow", "House"))
        self.button_canary.setText(_translate("MainWindow", "Canary"))

    def show_canary(self):
        self.photo.setPixmap(QtGui.QPixmap(root_folder + '/canary.jpg'))

    def show_house(self):
        self.photo.setPixmap(QtGui.QPixmap(root_folder + '/Roune.jpg'))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
